### ISSUE TITLE
Restore or replace toobusy

### ISSUE THREAD

**Issue by kethinov** [kethinov/roosevelt#31]
I had to disable toobusy because it was breaking npm installs of fresh roosevelt apps. Seems related to this: https://github.com/lloyd/node-toobusy/issues/45

**Comment by alallier** [comment]
Latest [comment](https://github.com/lloyd/node-toobusy/issues/45#issuecomment-76638534) on [lloyd/node-toobusy#45](https://github.com/lloyd/node-toobusy/issues/45) useful?

**Comment by kethinov** [comment]
Yeah, we'll most likely need to replace the module with something. That fork is a decent place to start looking.
