### ISSUE TITLE
Controller File Error Line Numbers

### ISSUE THREAD

**Issue by alallier** [kethinov/roosevelt#51]
It would be really helpful if the controller errors referenced line numbers so that you could easily go to the place with an error.

**Comment by kethinov** [comment]
Yeah that's a good idea. Submit a PR?

Here's where you'll want to do it: https://github.com/kethinov/roosevelt/blob/be0d995dc2dbfa92704a3c863196447eb1d71df1/lib/mapRoutes.js#L121

Possibly using something like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/lineNumber

**Comment by alallier** [comment]
Sure can!

**Comment by alallier** [comment]
`e.lineNumber` doesn't work in Node would you be opposed to printing the whole stack trace or is that too messy?

```
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:4
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at J:\My Documents\GitHub\X\no
tes.js:116:11
    at Array.forEach (native)
    at module.exports (J:\My Documents\GitHub\X\lib\mapRoutes.js:110:19)
    at module.exports (J:\My Documents\GitHub\X\roosevelt.js:64:35)
    at Object.<anonymous> (J:\My Documents\GitHub
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:4
    at Module.load (module.js:345:32)
```

Still investigating the possibility of just printing the line number without the whole stack trace

**Comment by kethinov** [comment]
Can you post before/after screenshots?

**Comment by alallier** [comment]
![image](https://cloud.githubusercontent.com/assets/13004518/13623678/60447c64-e576-11e5-8ecc-7e3482059bf3.png)

**Comment by kethinov** [comment]
So I take it the only difference is the stack trace you pasted being omitted in the current version?

**Comment by kethinov** [comment]
The stack trace is useful but we kind of need line number to seal the deal.

**Comment by alallier** [comment]
You're totally right I was reading the stack trace and thought it gave the line number error in the actual controller which it doesn't. I will have to do more digging and experimentation.

**Comment by Autre31415** [comment]
Using the latest roosevelt I created a controller error similar to @alallier's and I'm getting line numbers in it. Perhaps this issue sorted itself out with time?

![controller error](https://cloud.githubusercontent.com/assets/8182831/25247222/3e48bc76-25d8-11e7-8eca-cdd060dc76b9.png)

**Comment by alallier** [comment]
I can confirm this works, I just tested with a fresh sample app. Will close now.

**Comment by kethinov** [comment]
Oh cool. The new version of node must've changed how the error object works to do this by default.
