### ISSUE TITLE
Branch model

### ISSUE THREAD

**Issue by matthew-renodin** [kethinov/roosevelt#66]
<image src="https://images.moviepilot.com/images/c_limit,q_auto,w_710/alternate-ending-for-star-wars-episode-iii-fb5cded5-07c0-4382-830a-b5a569bb5631-jpeg-292832/alternate-ending-for-star-wars-episode-iii.jpg" />

Here is an alternative model for managing releases. I think this may help you manage your commit history minimization goals, squashing or rebasing commit comments, on your release branch without the need for developers removing or squashing.

http://nvie.com/posts/a-successful-git-branching-model/

**Comment by kethinov** [comment]
There are different schools of thought. I prefer the approach that requires the least hassle. It's the most messy, but I just don't see value in squashing commits, nor militantly enforcing that as a requirement.
