### ISSUE TITLE
Body parser extended undefined deprecated

### ISSUE THREAD

**Issue by alallier** [kethinov/roosevelt#67]
The body parser needs to explicitly specified whether or not extended is set to `true` or `false`. (See [here](http://stackoverflow.com/questions/25471856/express-throws-error-as-body-parser-deprecated-undefined-extended) and [here](https://github.com/expressjs/body-parser/blob/3f1b02247702c2966d33ee73610a98d54cf32fe8/lib/types/urlencoded.js#L41-L44)).

1. This can either be done by default in `setExpressConfigs.js` or 
2. Be done in the sample apps `package.json`

Option one is probably the safest

**Comment by kethinov** [comment]
Closed by https://github.com/kethinov/roosevelt/commit/757503e1f536aa5f3ef8b11aab497f5993bb5cda
