### ISSUE TITLE
Apps do not run outside of home directory in Windows

### ISSUE THREAD

**Issue by kethinov** [kethinov/roosevelt#7]
Attempting to create and run a Roosevelt app in some place like C:\ results in `EPERM, operation not permitted`.

They can only be run inside your home directory where administrator permissions are not required.

**Comment by kethinov** [comment]
@Autre31415 claims this is fixed now.

**Comment by Autre31415** [comment]
Spun up a new app in c:\testing in both windows 7 and 10 and had no issues. This can be closed
